-- ============================================
-- TORRES MOTORSPORT ENGINEERING - PARTS SEED DATA
-- Generado automáticamente desde parts.ts
-- Total de piezas: 126
-- ============================================

INSERT INTO parts (id, name, brand, category, price, weight, description, compatibility, stats)
VALUES
(
    'engine-rb26dett-nismo',
    'RB26DETT N1 Spec',
    'NISMO',
    'engine',
    45000,
    265,
    'El legendario motor RB26DETT en especificación N1 con bloque reforzado, pistones forjados y cigüeñal balanceado.',
    '{"mountTypes":["inline6"],"drivetrains":["AWD","RWD"],"engineLayouts":["front"],"minEngineBaySize":45}',
    '{"horsepowerAdd":120,"horsepowerMultiplier":1,"torqueAdd":100,"revLimit":9000}'
),
(
    'engine-2jz-gte-vvti',
    '2JZ-GTE VVT-i',
    'Toyota',
    'engine',
    25000,
    250,
    'Motor 2JZ-GTE con VVT-i, conocido por su increíble potencial de modificación y fiabilidad legendaria.',
    '{"mountTypes":["inline6"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"],"minEngineBaySize":42}',
    '{"horsepowerAdd":80,"horsepowerMultiplier":1,"torqueAdd":90,"revLimit":8200}'
),
(
    'engine-ls3-crate',
    'LS3 6.2L V8 Crate',
    'GM Performance',
    'engine',
    18000,
    210,
    'Motor LS3 de caja completo con 430hp de fábrica. Base perfecta para builds de alto rendimiento.',
    '{"mountTypes":["v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"],"minEngineBaySize":50}',
    '{"horsepowerAdd":130,"torqueAdd":150,"revLimit":6600}'
),
(
    'engine-l4-20-na',
    'L4 2.0 Atmosférico',
    'Torres Motorsport',
    'engine',
    4500,
    118,
    'Motor económico y fiable de 4 cilindros, ideal para coches compactos. Base perfecta para tuning ligero con excelente eficiencia de combustible.',
    '{"mountTypes":["inline4"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front"],"minEngineBaySize":25}',
    '{"horsepowerAdd":155,"torqueAdd":190,"revLimit":6500}'
),
(
    'engine-l4-20-turbo-s1',
    'L4 2.0 Turbo Stage 1',
    'Torres Motorsport',
    'engine',
    8500,
    130,
    'Motor turboalimentado de 2.0L con turbo pequeño para respuesta rápida. Perfecto para swaps económicos en compactos deportivos.',
    '{"mountTypes":["inline4"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front"],"minEngineBaySize":28}',
    '{"horsepowerAdd":245,"torqueAdd":320,"revLimit":6800,"boostPressure":0.8}'
),
(
    'engine-l4-23-turbo-s2',
    'L4 2.3 Turbo Stage 2',
    'Torres Motorsport',
    'engine',
    15000,
    137,
    'Motor 2.3L con turbo de mayor tamaño para potencia seria. Mayor lag pero entrega de potencia impresionante en rango medio-alto.',
    '{"mountTypes":["inline4"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front"],"minEngineBaySize":30}',
    '{"horsepowerAdd":360,"torqueAdd":450,"revLimit":7200,"boostPressure":1.4}'
),
(
    'engine-l4-25-race',
    'L4 2.5 Race-Spec',
    'Torres Motorsport',
    'engine',
    32000,
    140,
    'Motor de competición con internos forjados, culata portada y preparación completa. Requiere mantenimiento frecuente pero ofrece rendimiento extremo.',
    '{"mountTypes":["inline4"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front"],"minEngineBaySize":32}',
    '{"horsepowerAdd":480,"torqueAdd":520,"revLimit":9000,"boostPressure":2}'
),
(
    'engine-l6-30-na',
    'L6 3.0 Atmosférico',
    'Torres Motorsport',
    'engine',
    12000,
    165,
    'Motor 6 en línea atmosférico de alta durabilidad. Entrega suave de potencia ideal para coupés y sedanes premium.',
    '{"mountTypes":["inline6"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"],"minEngineBaySize":38}',
    '{"horsepowerAdd":260,"torqueAdd":310,"revLimit":7000}'
),
(
    'engine-l6-30-turbo-s1',
    'L6 3.0 Turbo Stage 1',
    'Torres Motorsport',
    'engine',
    18000,
    176,
    'Motor 6 en línea con turbo pequeño de spool rápido. Excelente equilibrio entre respuesta y potencia máxima.',
    '{"mountTypes":["inline6"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"],"minEngineBaySize":40}',
    '{"horsepowerAdd":380,"torqueAdd":450,"revLimit":7200,"boostPressure":0.9}'
),
(
    'engine-l6-34-turbo-s2',
    'L6 3.4 Turbo Stage 2',
    'Torres Motorsport',
    'engine',
    28000,
    180,
    'Motor 3.4L con turbo de alto flujo. Internos reforzados para soportar boost elevado y potencia seria.',
    '{"mountTypes":["inline6"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"],"minEngineBaySize":42}',
    '{"horsepowerAdd":520,"torqueAdd":610,"revLimit":7500,"boostPressure":1.5}'
),
(
    'engine-l6-34-race-dual-turbo',
    'L6 3.4 Race Dual Turbo',
    'Torres Motorsport',
    'engine',
    65000,
    185,
    'Motor legendario con sistema biturbo secuencial. Ideal para drift y grip profesional con entrega de potencia progresiva y brutal.',
    '{"mountTypes":["inline6"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"],"minEngineBaySize":45}',
    '{"horsepowerAdd":720,"torqueAdd":780,"revLimit":9000,"boostPressure":2.2}'
),
(
    'engine-v6-32-na',
    'V6 3.2 Atmosférico',
    'Torres Motorsport',
    'engine',
    10000,
    175,
    'Motor V6 atmosférico compacto con alta durabilidad. Sonido característico y entrega de potencia lineal.',
    '{"mountTypes":["v6"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid"],"minEngineBaySize":35}',
    '{"horsepowerAdd":290,"torqueAdd":340,"revLimit":7000}'
),
(
    'engine-v6-32-twin-turbo',
    'V6 3.2 Twin Turbo',
    'Torres Motorsport',
    'engine',
    25000,
    185,
    'V6 con configuración twin turbo simétrica. Excelente balance de peso y potencia impresionante.',
    '{"mountTypes":["v6"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid"],"minEngineBaySize":38}',
    '{"horsepowerAdd":480,"torqueAdd":610,"revLimit":7500,"boostPressure":1.2}'
),
(
    'engine-v6-35-race-tt',
    'V6 3.5 Race Twin Turbo',
    'Torres Motorsport',
    'engine',
    42000,
    190,
    'Motor V6 de competición con twin turbo de alto rendimiento. Preparado para pista con internos forjados y lubricación mejorada.',
    '{"mountTypes":["v6"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"],"minEngineBaySize":40}',
    '{"horsepowerAdd":650,"torqueAdd":760,"revLimit":8500,"boostPressure":1.8}'
),
(
    'engine-v8-50-na',
    'V8 5.0 Atmosférico',
    'Torres Motorsport',
    'engine',
    15000,
    220,
    'Motor V8 americano clásico atmosférico. Torque abundante desde bajas RPM y sonido muscle car icónico.',
    '{"mountTypes":["v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"],"minEngineBaySize":48}',
    '{"horsepowerAdd":410,"torqueAdd":550,"revLimit":7000}'
),
(
    'engine-v8-50-supercharged',
    'V8 5.0 Supercharged',
    'Torres Motorsport',
    'engine',
    28000,
    235,
    'V8 con compresor volumétrico para respuesta instantánea sin lag. Potencia brutal disponible desde el ralentí.',
    '{"mountTypes":["v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"],"minEngineBaySize":52}',
    '{"horsepowerAdd":580,"torqueAdd":720,"revLimit":7200,"boostPressure":0.9}'
),
(
    'engine-v8-62-twin-turbo',
    'V8 6.2 Twin Turbo',
    'Torres Motorsport',
    'engine',
    48000,
    250,
    'Motor V8 de gran cilindrada con twin turbo. Combina el torque del V8 americano con la potencia máxima del turbo.',
    '{"mountTypes":["v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"],"minEngineBaySize":55}',
    '{"horsepowerAdd":780,"torqueAdd":890,"revLimit":7500,"boostPressure":1.4}'
),
(
    'engine-v8-62-race-pro',
    'V8 6.2 Race Pro',
    'Torres Motorsport',
    'engine',
    85000,
    245,
    'Motor V8 de competición profesional. Bloque reforzado, cigüeñal de acero billet y sistema de válvulas de titanio.',
    '{"mountTypes":["v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"],"minEngineBaySize":55}',
    '{"horsepowerAdd":920,"torqueAdd":950,"revLimit":9000,"boostPressure":2}'
),
(
    'engine-v10-50-race',
    'V10 5.0 Race',
    'Torres Motorsport',
    'engine',
    75000,
    240,
    'Motor V10 de alta revolución inspirado en F1. Sonido único y entrega de potencia lineal hasta el corte de inyección.',
    '{"mountTypes":["v10"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"],"minEngineBaySize":50}',
    '{"horsepowerAdd":620,"torqueAdd":540,"revLimit":9500}'
),
(
    'engine-v12-60-na',
    'V12 6.0 Atmosférico',
    'Torres Motorsport',
    'engine',
    95000,
    270,
    'Motor V12 atmosférico de lujo. Suavidad excepcional, potencia abundante y sonido de supercar italiano.',
    '{"mountTypes":["v12"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"],"minEngineBaySize":60}',
    '{"horsepowerAdd":580,"torqueAdd":620,"revLimit":8500}'
),
(
    'engine-v12-65-race',
    'V12 6.5 Race Extreme',
    'Torres Motorsport',
    'engine',
    180000,
    265,
    'El motor definitivo. V12 de competición con internos de titanio, lubricación de carter seco y más de 10,000 RPM.',
    '{"mountTypes":["v12"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"],"minEngineBaySize":65}',
    '{"horsepowerAdd":950,"torqueAdd":780,"revLimit":10200}'
),
(
    'engine-rotary-13b-turbo',
    'Rotativo 13B Turbo',
    'Torres Motorsport',
    'engine',
    22000,
    122,
    'Motor rotativo Wankel con turbocompresor. Peso ultraligero, alto régimen de giro y sonido inconfundible.',
    '{"mountTypes":["rotary"],"drivetrains":["RWD"],"engineLayouts":["front"],"minEngineBaySize":30}',
    '{"horsepowerAdd":350,"torqueAdd":320,"revLimit":9500,"boostPressure":1}'
),
(
    'engine-electric-400kw',
    'Motor Eléctrico Performance 400kW',
    'Torres Motorsport',
    'engine',
    45000,
    310,
    'Motor eléctrico de alto rendimiento con par instantáneo de 900 Nm. Sin necesidad de caja de cambios tradicional.',
    '{"mountTypes":["electric"],"drivetrains":["RWD","AWD","FWD"],"engineLayouts":["front","mid","rear"],"minEngineBaySize":25}',
    '{"horsepowerAdd":540,"torqueAdd":900,"revLimit":15000}'
),
(
    'turbo-garrett-gtx3582r',
    'GTX3582R Gen II',
    'Garrett',
    'turbo',
    3500,
    12,
    'Turbo de alta eficiencia con compresor de rueda de palas forjadas. Spool rápido y potencia sostenida.',
    '{"mountTypes":["inline4","inline6","v6"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":180,"torqueAdd":150,"boostPressure":1.2,"boostEfficiency":0.78}'
),
(
    'turbo-precision-6266',
    'PT6266 CEA',
    'Precision Turbo',
    'turbo',
    4200,
    14,
    'Turbo de competición con tecnología CEA para máximo flujo de aire y respuesta.',
    '{"mountTypes":["inline6","v6","v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"],"minEngineBaySize":40}',
    '{"horsepowerAdd":280,"torqueAdd":220,"boostPressure":1.8,"boostEfficiency":0.82}'
),
(
    'turbo-borg-s366',
    'S366 SX-E',
    'BorgWarner',
    'turbo',
    2200,
    10,
    'Turbo versátil ideal para builds de calle con buen spool y potencia lineal.',
    '{"mountTypes":["inline4","inline6","v6","flat4"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerAdd":120,"torqueAdd":100,"boostPressure":0.9,"boostEfficiency":0.72}'
),
(
    'turbo-garrett-gt28r',
    'Garrett GT28R',
    'Garrett',
    'turbo',
    1299,
    7.2,
    'Turbo compacto GT28R, rápido spool y buena eficiencia para 200-380 hp. Ideal para motores 2.0-2.5L.',
    '{"mountTypes":["inline4","inline6"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":140,"torqueAdd":120,"boostPressure":1.7,"boostEfficiency":0.72}'
),
(
    'turbo-borgwarner-efr-gt30',
    'BorgWarner EFR GT30',
    'BorgWarner',
    'turbo',
    2199,
    8.5,
    'Turbo GT30 de alto rendimiento, buena respuesta y rango medio-alto. Soporta 350-500hp con eficiencia.',
    '{"mountTypes":["inline4","inline6","v6"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":200,"torqueAdd":180,"boostPressure":1.9,"boostEfficiency":0.78}'
),
(
    'turbo-precision-gt35',
    'Precision GT35',
    'Precision Turbo',
    'turbo',
    2899,
    11,
    'GT35 para builds de +500hp. Mayor flujo y robustez para carreras y street tuning serio.',
    '{"mountTypes":["inline6","v6","v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":280,"torqueAdd":250,"boostPressure":2.3,"boostEfficiency":0.8}'
),
(
    'turbo-comp-twinkit-s200',
    'Comp Turbo Twin-Kit S200',
    'Comp Turbo',
    'turbo',
    6599,
    24,
    'Kit twin-turbo balanceado para motores inline-6 y V6; incluye actuadores, juntas y mapeo base.',
    '{"mountTypes":["inline6","v6","v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":380,"torqueAdd":350,"boostPressure":2.4,"boostEfficiency":0.82}'
),
(
    'turbo-precision-gt40',
    'Precision GT40',
    'Precision Turbo',
    'turbo',
    4999,
    13.5,
    'GT40 para aplicaciones +700hp. Requiere gestión avanzada y sistema de combustible reforzado.',
    '{"mountTypes":["inline6","v6","v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":450,"torqueAdd":400,"boostPressure":2.7,"boostEfficiency":0.75}'
),
(
    'turbo-ihi-vf34',
    'IHI VF34',
    'IHI',
    'turbo',
    799,
    6,
    'Turbo OEM-style de bajo coste, ideal para swaps económicos y street builds 180-260hp.',
    '{"mountTypes":["inline4","flat4"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":90,"torqueAdd":80,"boostPressure":1.5,"boostEfficiency":0.68}'
),
(
    'turbo-garrett-gtx2867r',
    'Garrett GTX2867R',
    'Garrett',
    'turbo',
    1899,
    7.8,
    'Turbo de respuesta rápida con rueda de palas fresadas. Ideal para 300-450hp.',
    '{"mountTypes":["inline4","inline6"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":160,"torqueAdd":140,"boostPressure":1.8,"boostEfficiency":0.76}'
),
(
    'turbo-hks-gt3-ss',
    'HKS GT Supercharger III SS',
    'HKS',
    'turbo',
    3299,
    9.5,
    'Turbo premium japonés con diseño de doble entrada. Excelente para builds JDM de alto rendimiento.',
    '{"mountTypes":["inline6","v6"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":220,"torqueAdd":200,"boostPressure":2,"boostEfficiency":0.8}'
),
(
    'turbo-turbonetics-t76',
    'Turbonetics T76',
    'Turbonetics',
    'turbo',
    3599,
    12,
    'Turbo de gran tamaño para builds de drag y alto boost. Soporta hasta 900hp.',
    '{"mountTypes":["inline6","v6","v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":350,"torqueAdd":320,"boostPressure":2.5,"boostEfficiency":0.77}'
),
(
    'turbo-borg-efr-7670',
    'BorgWarner EFR 7670',
    'BorgWarner',
    'turbo',
    2799,
    9.8,
    'Turbo EFR de última generación con tecnología Gamma-Ti. Respuesta excepcional.',
    '{"mountTypes":["inline4","inline6","v6"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":240,"torqueAdd":210,"boostPressure":2.1,"boostEfficiency":0.81}'
),
(
    'turbo-garrett-g25-660',
    'Garrett G25-660',
    'Garrett',
    'turbo',
    1699,
    6.5,
    'Turbo compacto G-Series con respuesta ultrarrápida. Perfecto para hot hatches y compactos.',
    '{"mountTypes":["inline4"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":130,"torqueAdd":110,"boostPressure":1.6,"boostEfficiency":0.74}'
),
(
    'turbo-full-race-twinscroll',
    'Full-Race Twin-Scroll Kit',
    'Full-Race',
    'turbo',
    4299,
    15,
    'Kit completo twin-scroll con manifold y wastegate externa. Mejora spool y eficiencia.',
    '{"mountTypes":["inline4","inline6"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":260,"torqueAdd":230,"boostPressure":2,"boostEfficiency":0.83}'
),
(
    'super-whipple-2-3',
    'Whipple 2.3L Twin-Screw',
    'Whipple',
    'supercharger',
    8999,
    48,
    'Twin-screw sobredimensionado, entrega respuesta instantánea y +200-350hp según tuneo. Requiere gestión avanzada.',
    '{"mountTypes":["v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":300,"torqueAdd":280,"boostPressure":0.8,"boostEfficiency":0.85}'
),
(
    'super-vortech-v3',
    'Vortech Centrifugal V-3',
    'Vortech',
    'supercharger',
    5799,
    32,
    'Compresor centrífugo con curva de potencia que emula turbo pero con respuesta mecánica; +120-300hp según montaje.',
    '{"mountTypes":["v6","v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":220,"torqueAdd":180,"boostPressure":0.7,"boostEfficiency":0.78}'
),
(
    'super-kennebell-2-8',
    'Kenne Bell Twin-Screw 2.8L',
    'Kenne Bell',
    'supercharger',
    10499,
    52,
    'Kit premium twin-screw con sobremarcha alta y mapeo para +300-450hp. Uso track/drag.',
    '{"mountTypes":["v8"],"drivetrains":["RWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":380,"torqueAdd":350,"boostPressure":0.9,"boostEfficiency":0.88}'
),
(
    'super-eaton-tvs-1900',
    'Eaton Roots TVS 1900',
    'Eaton',
    'supercharger',
    4499,
    42,
    'Roots clásico, buen empuje desde bajas rpm. +100-200hp, confiable y compacto.',
    '{"mountTypes":["v6","v8"],"drivetrains":["FWD","RWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":140,"torqueAdd":160,"boostPressure":0.55,"boostEfficiency":0.72}'
),
(
    'super-procharger-p1sc',
    'ProCharger P-1SC-1',
    'ProCharger',
    'supercharger',
    6299,
    35,
    'Centrífugo de alto rendimiento con intercooler integrado. Excelente para muscle cars.',
    '{"mountTypes":["v8"],"drivetrains":["RWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":260,"torqueAdd":220,"boostPressure":0.75,"boostEfficiency":0.8}'
),
(
    'super-magnuson-tvs2300',
    'Magnuson TVS2300',
    'Magnuson',
    'supercharger',
    7499,
    45,
    'Supercargador Roots de alta eficiencia con diseño TVS de 4 lóbulos. Excelente torque bajo.',
    '{"mountTypes":["v6","v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":200,"torqueAdd":240,"boostPressure":0.6,"boostEfficiency":0.76}'
),
(
    'super-roush-r2300',
    'Roush R2300 TVS',
    'Roush',
    'supercharger',
    8299,
    46,
    'Kit completo de supercargador para Mustang y F-150 con hasta +400hp.',
    '{"mountTypes":["v8"],"drivetrains":["RWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":320,"torqueAdd":300,"boostPressure":0.8,"boostEfficiency":0.82}'
),
(
    'super-jackson-racing',
    'Jackson Racing C38',
    'Jackson Racing',
    'supercharger',
    3999,
    28,
    'Supercargador centrífugo para motores de 4 cilindros. Ideal para Miatas y 86/BRZ.',
    '{"mountTypes":["inline4","flat4"],"drivetrains":["FWD","RWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":120,"torqueAdd":100,"boostPressure":0.5,"boostEfficiency":0.74}'
),
(
    'exhaust-tomei-expreme',
    'Expreme Ti Full',
    'Tomei',
    'exhaust',
    3800,
    -8,
    'Sistema de escape completo en titanio. Máximo flujo y sonido de competición.',
    '{"mountTypes":["inline4","inline6","flat4","flat6"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerAdd":25,"torqueAdd":15,"weightReduction":15}'
),
(
    'exhaust-akrapovic-evolution',
    'Evolution Line Titanium',
    'Akrapovič',
    'exhaust',
    6500,
    -12,
    'Sistema de escape de competición en titanio con colectores optimizados por CFD.',
    '{"mountTypes":["inline4","inline6","v6","v8","flat6"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerAdd":35,"torqueAdd":25,"weightReduction":20}'
),
(
    'exhaust-hks-hipower',
    'Hi-Power Spec-L II',
    'HKS',
    'exhaust',
    1800,
    -5,
    'Sistema catback de acero inoxidable con silenciador de alto flujo.',
    '{"mountTypes":["inline4","inline6","v6","flat4"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerAdd":15,"torqueAdd":10,"weightReduction":8}'
),
(
    'exhaust-borla-catback-ss',
    'Borla Cat-Back S-Type',
    'Borla',
    'exhaust',
    999,
    12.5,
    'Sistema catback en acero inoxidable, tono profundo y ligera mejora de flujo.',
    '{"mountTypes":["inline4","inline6","v6","v8"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerAdd":7,"torqueAdd":5,"weightReduction":3}'
),
(
    'exhaust-akrapovic-full-ti',
    'Akrapovič Full Titanium',
    'Akrapovič',
    'exhaust',
    8999,
    6,
    'Sistema completo en titanio, máxima reducción de peso y rendimiento, sonido agresivo con pop on overrun.',
    '{"mountTypes":["inline6","v6","v8","flat6"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerAdd":18,"torqueAdd":12,"weightReduction":18}'
),
(
    'exhaust-hks-header',
    'HKS Racing Header',
    'HKS',
    'exhaust',
    679,
    9.5,
    'Colectores de escape de acero inoxidable para mejor evacuación y torque medio-alto.',
    '{"mountTypes":["inline4","inline6"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":12,"torqueAdd":10}'
),
(
    'exhaust-invidia-downpipe',
    'Invidia High Flow Downpipe',
    'Invidia',
    'exhaust',
    399,
    7.8,
    'Downpipe de alto flujo, reduce contrapresión de turbocompresores; requiere reprogramación ECU.',
    '{"mountTypes":["inline4","inline6","flat4"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":15,"torqueAdd":12,"weightReduction":2}'
),
(
    'exhaust-capristo-titanium',
    'Capristo Titanium Sport',
    'Capristo',
    'exhaust',
    5299,
    8,
    'Sistema sport titanio, diseñado para coches exóticos y GTs con equilibrio entre sonido y prestaciones.',
    '{"mountTypes":["v8","v10","v12"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerAdd":14,"torqueAdd":10,"weightReduction":12}'
),
(
    'exhaust-magnaflow-catback',
    'MagnaFlow Catback Performance',
    'MagnaFlow',
    'exhaust',
    749,
    13,
    'Catback equilibrado para uso diario y circuito, duradero y con buen tono.',
    '{"mountTypes":["inline4","inline6","v6","v8"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerAdd":8,"torqueAdd":6,"weightReduction":4}'
),
(
    'exhaust-testpipe-highflow',
    'Test Pipe High Flow',
    'Vibrant',
    'exhaust',
    149,
    4.2,
    'Test pipe (sin catalizador) para circuito. Aumenta flujo pero no legal para calle.',
    '{"mountTypes":["inline4","inline6","v6"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":10,"torqueAdd":8,"weightReduction":2}'
),
(
    'exhaust-kooks-headers',
    'Kooks Long Tube Headers',
    'Kooks',
    'exhaust',
    1299,
    14,
    'Headers de tubo largo para V8 americanos. Máximo flujo y sonido muscle car.',
    '{"mountTypes":["v8"],"drivetrains":["RWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":25,"torqueAdd":20,"weightReduction":5}'
),
(
    'exhaust-flowmaster-catback',
    'Flowmaster American Thunder',
    'Flowmaster',
    'exhaust',
    599,
    15,
    'Sistema catback con sonido muscle car agresivo. Diseño de cámara resonante.',
    '{"mountTypes":["v6","v8"],"drivetrains":["RWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":6,"torqueAdd":8}'
),
(
    'exhaust-ipe-valvetronic',
    'iPE Valvetronic F1',
    'iPE',
    'exhaust',
    7499,
    9,
    'Sistema con válvulas controlables para alternar entre modo silencioso y racing.',
    '{"mountTypes":["v6","v8","v10","v12"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerAdd":16,"torqueAdd":12,"weightReduction":10}'
),
(
    'intake-aem-cold',
    'Cold Air Intake System',
    'AEM',
    'intake',
    450,
    2,
    'Sistema de admisión de aire frío con filtro de alto flujo y tubo mandrel-bent.',
    '{"mountTypes":["inline4","inline6","v6","v8","flat4","flat6"],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerAdd":12,"torqueAdd":8}'
),
(
    'intake-gruppe-m-carbon',
    'Carbon Fiber Ram Air',
    'GruppeM',
    'intake',
    2200,
    -2,
    'Sistema de admisión en fibra de carbono con efecto ram air a alta velocidad.',
    '{"mountTypes":["inline6","v6","v8","flat6"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":22,"torqueAdd":15,"weightReduction":3}'
),
(
    'ecu-haltech-elite-2500',
    'Elite 2500',
    'Haltech',
    'ecu',
    2800,
    1,
    'ECU standalone de alto rendimiento con control completo del motor y data logging.',
    '{"mountTypes":["inline4","inline6","v6","v8","flat4","flat6","rotary"],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerMultiplier":1.08,"torqueMultiplier":1.05}'
),
(
    'ecu-motec-m150',
    'M150 GPR',
    'MoTeC',
    'ecu',
    8500,
    1,
    'La ECU de competición definitiva. Usada en campeonatos mundiales de rally y circuito.',
    '{"mountTypes":["inline4","inline6","v6","v8","flat4","flat6","rotary"],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerMultiplier":1.12,"torqueMultiplier":1.08}'
),
(
    'intake-aem-coldair',
    'AEM Cold Air Intake',
    'AEM',
    'intake',
    299,
    3.2,
    'Admisión de aire frío con filtro de alto flujo. Mejora par bajo-medio.',
    '{"mountTypes":["inline4","inline6","v6","v8"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":6,"torqueAdd":5}'
),
(
    'intake-eventuri-carbon',
    'Eventuri Carbon Ram Air',
    'Eventuri',
    'intake',
    799,
    2.4,
    'Sistema ram air en fibra de carbono, optimizado para respuesta y flujo en gama alta.',
    '{"mountTypes":["inline6","v6","v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":12,"torqueAdd":8,"coolingEfficiency":0.05}'
),
(
    'intake-jenvey-itb',
    'Jenvey Individual Throttle Bodies Kit',
    'Jenvey',
    'intake',
    3299,
    10,
    'ITB para motores de altas RPM, mejora respuesta y pico de potencia. Requiere gestión y map tuning.',
    '{"mountTypes":["inline4","inline6"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":25,"torqueAdd":15,"horsepowerMultiplier":1.05}'
),
(
    'intake-kn-filter',
    'K&N High-Flow Filter',
    'K&N',
    'intake',
    49,
    0.4,
    'Filtro lavable de alto flujo, fácil instalación. Mejora mínima pero económica.',
    '{"mountTypes":["inline4","inline6","v6","v8","flat4","flat6","rotary"],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerAdd":2}'
),
(
    'intake-skunk2-manifold',
    'Skunk2 Intake Manifold (High-Flow)',
    'Skunk2',
    'intake',
    899,
    6.5,
    'Colector de admisión rendimiento, mejora respuesta y potencia alta.',
    '{"mountTypes":["inline4"],"drivetrains":["FWD","RWD"],"engineLayouts":["front"]}',
    '{"horsepowerAdd":18,"torqueAdd":12}'
),
(
    'intake-gruppem-ram',
    'GruppeM Ram Intake',
    'GruppeM',
    'intake',
    1199,
    3,
    'Sistema ram premium para elevadas entradas de aire frío. Acabado en carbono real.',
    '{"mountTypes":["inline6","v6","v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":10,"torqueAdd":8}'
),
(
    'intake-hks-boostpipe',
    'HKS Boost Pipe Kit',
    'HKS',
    'intake',
    249,
    2,
    'Tubería y couplings reforzados para sistemas turbo, soporta altas presiones.',
    '{"mountTypes":["inline4","inline6","flat4"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front"]}',
    '{"boostEfficiency":0.05}'
),
(
    'intake-aem-ram-universal',
    'AEM Universal Ram Air',
    'AEM',
    'intake',
    349,
    3.6,
    'Ram air universal con adaptadores, mejora eficiencia a alta velocidad.',
    '{"mountTypes":["inline4","inline6","v6","v8"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerAdd":8,"torqueAdd":5}'
),
(
    'ecu-haltech-elite750',
    'Haltech Elite 750',
    'Haltech',
    'ecu',
    3999,
    1.2,
    'Standalone ECU para builds avanzados con logging y control completo de inyección, ignición y boost.',
    '{"mountTypes":["inline4","inline6","v6","v8","flat4","rotary"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerMultiplier":1.15,"torqueMultiplier":1.12}'
),
(
    'ecu-motec-m1',
    'MoTeC M1',
    'MoTeC',
    'ecu',
    11999,
    1,
    'ECU profesional usado en competición. Control total para mapas, telemetría y sistemas avanzados.',
    '{"mountTypes":["inline4","inline6","v6","v8","v10","v12","flat6","rotary"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerMultiplier":1.22,"torqueMultiplier":1.18}'
),
(
    'ecu-aem-infinity',
    'AEM Infinity EMU',
    'AEM',
    'ecu',
    6499,
    1.1,
    'Standalone de nivel medio-alto con herramientas de mapeo y funciones anti-lag.',
    '{"mountTypes":["inline4","inline6","v6","v8","flat4"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerMultiplier":1.12,"torqueMultiplier":1.1}'
),
(
    'ecu-cobb-accessport',
    'Cobb Accessport V3',
    'Cobb',
    'ecu',
    599,
    0.3,
    'Flash tuner para coches compatibles, mapas stage 1-3, fácil instalación.',
    '{"mountTypes":["inline4","flat4"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front"]}',
    '{"horsepowerMultiplier":1.08,"torqueMultiplier":1.06}'
),
(
    'ecu-jb4-piggyback',
    'JB4 Tuning Module',
    'Burger Motorsports',
    'ecu',
    499,
    0.2,
    'Piggyback para intercambiar mapas sin reemplazar ECU; funciona bien con turbomotores.',
    '{"mountTypes":["inline4","inline6","v6","v8"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front"]}',
    '{"horsepowerMultiplier":1.06,"torqueMultiplier":1.05}'
),
(
    'ecu-link-g4x',
    'Link G4X Xtreme',
    'Link ECU',
    'ecu',
    2499,
    0.8,
    'ECU standalone de excelente relación calidad-precio con capacidades avanzadas.',
    '{"mountTypes":["inline4","inline6","v6","flat4","rotary"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"horsepowerMultiplier":1.1,"torqueMultiplier":1.08}'
),
(
    'ecu-syvecs-s8',
    'Syvecs S8',
    'Syvecs',
    'ecu',
    8999,
    1,
    'ECU profesional para GT y prototipos con control de tracción avanzado y telemetría.',
    '{"mountTypes":["inline6","v6","v8","v10","v12"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"horsepowerMultiplier":1.18,"torqueMultiplier":1.15}'
),
(
    'trans-holinger-rd6',
    'RD6 Sequential',
    'Holinger',
    'transmission',
    18000,
    45,
    'Caja secuencial de 6 velocidades de competición. Cambios en 50ms.',
    '{"mountTypes":["inline4","inline6","v6","v8"],"drivetrains":["RWD"],"engineLayouts":["front","mid"]}',
    '{"gearRatios":[3.07,2.13,1.59,1.24,1,0.85],"clutchCapacity":1200}'
),
(
    'trans-getrag-dcl600',
    'DCL600 Dual Clutch',
    'GETRAG',
    'transmission',
    12000,
    78,
    'Transmisión de doble embrague de 6 velocidades. Perfecta para uso en calle y circuito.',
    '{"mountTypes":["inline4","inline6","v6","v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front"]}',
    '{"gearRatios":[3.92,2.41,1.58,1.19,0.94,0.76],"clutchCapacity":800}'
),
(
    'transmission-getrag-6-close',
    'Getrag 6-Speed Close Ratio',
    'Getrag',
    'transmission',
    3599,
    65,
    'Caja 6 velocidades con relaciones cerradas ideal para deportivos; mejora aceleración y paso de marcha.',
    '{"mountTypes":["inline4","inline6","v6"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"gearRatios":[3.58,2.19,1.52,1.18,0.94,0.78],"clutchCapacity":650}'
),
(
    'transmission-holinger-seq',
    'Holinger Sequential Pro',
    'Holinger',
    'transmission',
    14999,
    55,
    'Caja secuencial para competición; cambios ultrarrápidos, mantenimiento elevado.',
    '{"mountTypes":["inline4","inline6","v6","v8"],"drivetrains":["RWD"],"engineLayouts":["front","mid"]}',
    '{"gearRatios":[2.92,2.08,1.64,1.35,1.13,0.96],"clutchCapacity":1200}'
),
(
    'transmission-dsg-upgrade',
    'DSG Performance Upgrade',
    'ShepTrans',
    'transmission',
    3999,
    80,
    'Upgrade para cajas DCT/DSG: embragues y software para mayor capacidad y respuesta.',
    '{"mountTypes":["inline4","v6"],"drivetrains":["FWD","AWD"],"engineLayouts":["front"]}',
    '{}'
),
(
    'transmission-shortshifter-twm',
    'Short Shifter Kit TWM',
    'TWM',
    'transmission',
    189,
    1.3,
    'Kit short-shifter para reducir recorrido de cambio, mejora sensación y rapidez.',
    '{"mountTypes":["inline4","inline6","v6","v8"],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{}'
),
(
    'transmission-albins-st6',
    'Albins ST6 Sequential',
    'Albins',
    'transmission',
    18999,
    52,
    'Caja secuencial de competición profesional con dog rings de cromo-moly.',
    '{"mountTypes":["inline6","v6","v8"],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid"]}',
    '{"gearRatios":[2.75,1.94,1.52,1.24,1.04,0.89],"clutchCapacity":1400}'
),
(
    'differential-cusco-1way',
    'Cusco 1-Way LSD',
    'Cusco',
    'differential',
    1499,
    18,
    'LSD mecánico 1-way diseñado para tracción trasera; buen bloqueo en aceleración.',
    '{"mountTypes":[],"drivetrains":["RWD"],"engineLayouts":["front","mid","rear"]}',
    '{"limitedSlipRatio":0.4}'
),
(
    'differential-wavetrac-lsd',
    'Wavetrac Limited Slip',
    'Wavetrac',
    'differential',
    1899,
    20,
    'LSD avanzado para manejo suave y control en situaciones variables; ideal para circuito y carretera.',
    '{"mountTypes":[],"drivetrains":["AWD","RWD"],"engineLayouts":["front","mid","rear"]}',
    '{"limitedSlipRatio":0.5}'
),
(
    'differential-kaaz-2way',
    'Kaaz 2-Way Super Q',
    'Kaaz',
    'differential',
    1699,
    19,
    'LSD de 2 vías para drift profesional. Bloqueo agresivo en aceleración y desaceleración.',
    '{"mountTypes":[],"drivetrains":["RWD"],"engineLayouts":["front","mid"]}',
    '{"limitedSlipRatio":0.7}'
),
(
    'differential-os-giken-superlock',
    'OS Giken Superlock LSD',
    'OS Giken',
    'differential',
    2999,
    22,
    'El LSD definitivo para competición. Diseño multiplacas con ajuste de precarga.',
    '{"mountTypes":[],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"limitedSlipRatio":0.8}'
),
(
    'suspension-bc-br-coilover',
    'BC Racing BR Coilover',
    'BC Racing',
    'suspension',
    899,
    25,
    'Coilovers ajustables en altura, buena relación calidad/precio para street y track ligero.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"springRate":9.5,"dampingRate":6,"rideHeight":-25}'
),
(
    'suspension-ohlins-race-dfv',
    'Öhlins Road & Track DFV',
    'Öhlins',
    'suspension',
    4999,
    28,
    'Coilovers premium con damping multi-stage y alto control dinámico para circuito.',
    '{"mountTypes":[],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"springRate":12,"dampingRate":9,"rideHeight":-30}'
),
(
    'suspension-airlift-performance',
    'Air Lift Performance 3P',
    'Air Lift',
    'suspension',
    2199,
    35,
    'Kit de suspensión neumática para stance y comodidad ajustable vía compresor y app.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"rideHeight":-60,"dampingRate":5}'
),
(
    'suspension-eibach-prokit',
    'Eibach Pro-Kit Springs',
    'Eibach',
    'suspension',
    299,
    6.5,
    'Muelles deportivos para rebajar centro de gravedad sin perder confort.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"springRate":8,"rideHeight":-20}'
),
(
    'suspension-whiteline-sways',
    'Whiteline Anti-Roll Set',
    'Whiteline',
    'suspension',
    399,
    5,
    'Barras estabilizadoras ajustables para reducir balanceo de carrocería en curvas.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"antiRollBar":1.3}'
),
(
    'suspension-spc-controlarms',
    'SPC Adjustable Control Arms',
    'SPC',
    'suspension',
    349,
    4,
    'Brazos regulables para corregir geometría y camber tras modificación de suspensión.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"camber":1.5}'
),
(
    'suspension-penske-track',
    'Penske Track Shock',
    'Penske',
    'suspension',
    7499,
    14,
    'Amortiguadores de competición para coches preparados, ajuste de compresión y rebote.',
    '{"mountTypes":[],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"dampingRate":10,"springRate":14}'
),
(
    'suspension-tein-street-advance',
    'Tein Street Advance Z',
    'Tein',
    'suspension',
    1199,
    26,
    'Coilovers Street con buen confort y control; ajuste rápido para calle y track ligero.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"springRate":10,"dampingRate":6.5,"rideHeight":-35}'
),
(
    'brakes-brembo-6pot',
    'Brembo GT 6-Piston Kit',
    'Brembo',
    'brakes',
    4899,
    24,
    'Big brake kit 6 pistones con discos ranurados, excelente disipación para track.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"brakingPower":1.65,"heatResistance":0.95,"weightReduction":6}'
),
(
    'brakes-apracing-4pot',
    'AP Racing 4-Piston Kit',
    'AP Racing',
    'brakes',
    2499,
    28,
    'Kit de 4 pistones con discos ventilados, balance para competición y calle.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"brakingPower":1.45,"heatResistance":0.9}'
),
(
    'brakes-stoptech-sport',
    'StopTech Sport Stop Kit',
    'StopTech',
    'brakes',
    1199,
    16,
    'Mejora de freno para uso en carretera y trackday, incluye líneas metálicas y pastillas deportivas.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"brakingPower":1.3,"heatResistance":0.82}'
),
(
    'brakes-dba-t3-slotted',
    'DBA T3 Slotted Rotor Set',
    'DBA',
    'brakes',
    399,
    10,
    'Discos ranurados con ranuras optimizadas para disipación y limpieza de pastilla.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"brakingPower":1.12,"heatResistance":0.75}'
),
(
    'brakes-brembo-ceramic',
    'Brembo Carbon-Ceramic Kit',
    'Brembo',
    'brakes',
    14999,
    9,
    'Kit tope de gama para vehículos superdeportivos. Máxima disipación y mínimo peso.',
    '{"mountTypes":[],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"brakingPower":1.9,"heatResistance":0.98,"weightReduction":30}'
),
(
    'brakes-hawk-pads',
    'Hawk Performance Pads',
    'Hawk',
    'brakes',
    129,
    1.2,
    'Pastillas deportivas para uso mixto calle/track con buena mordida.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"brakingPower":1.1}'
),
(
    'brakes-stoptech-lines',
    'StopTech Stainless Lines',
    'StopTech',
    'brakes',
    179,
    0.8,
    'Latiguillos metálicos para mejorar sensación de pedal y respuesta.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"brakeBalance":0.52}'
),
(
    'brakes-ate-fluid',
    'ATE Super Blue Racing Fluid',
    'ATE',
    'brakes',
    39,
    1,
    'Líquido de frenos de alto punto de ebullición para resistir fade en pista.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"heatResistance":0.9}'
),
(
    'sus-ohlins-road-track',
    'Road & Track DFV',
    'Öhlins',
    'suspension',
    4500,
    25,
    'Suspensión coilover con tecnología DFV para máximo control y confort.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"springRate":10,"dampingRate":12,"rideHeight":-35}'
),
(
    'sus-kw-clubsport',
    'Clubsport 3-Way',
    'KW Suspensions',
    'suspension',
    7200,
    28,
    'Coilovers de 3 vías con ajuste independiente de bump, rebound y compresión.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"springRate":14,"dampingRate":16,"rideHeight":-45,"camber":-2.5}'
),
(
    'sus-bc-br-series',
    'BR Series Coilovers',
    'BC Racing',
    'suspension',
    1200,
    22,
    'Coilovers de entrada con 30 niveles de ajuste de amortiguación.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"springRate":8,"dampingRate":8,"rideHeight":-25}'
),
(
    'brakes-brembo-gt',
    'GT Big Brake Kit',
    'Brembo',
    'brakes',
    5500,
    8,
    'Kit de frenos grandes con pinzas de 6 pistones y discos de 380mm.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"brakingPower":1.35,"brakeBalance":58,"heatResistance":1.4}'
),
(
    'brakes-ap-racing-radi-cal',
    'Radi-CAL Pro 5000+',
    'AP Racing',
    'brakes',
    9500,
    -5,
    'Sistema de frenos de competición con pinzas monobloque de aluminio forjado.',
    '{"mountTypes":[],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"brakingPower":1.55,"brakeBalance":60,"heatResistance":1.8,"weightReduction":12}'
),
(
    'wheels-volk-te37',
    'TE37 Saga SL',
    'RAYS Volk Racing',
    'wheels',
    4800,
    -8,
    'Las legendarias TE37 en versión Super Lap. Forjadas en una pieza.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"],"boltPatterns":["5x100","5x108","5x112","5x114.3","5x120"]}',
    '{"wheelSize":18,"wheelWidth":9.5,"weightReduction":12}'
),
(
    'wheels-bbs-fi-r',
    'FI-R Forged',
    'BBS',
    'wheels',
    8500,
    -12,
    'Llantas forjadas de competición con diseño aerodinámico optimizado.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"],"boltPatterns":["5x112","5x114.3","5x120","5x130"]}',
    '{"wheelSize":19,"wheelWidth":10,"weightReduction":18}'
),
(
    'wheels-enkei-rpf1',
    'RPF1',
    'Enkei',
    'wheels',
    1800,
    -4,
    'Llantas de flujo MAT ligeras y resistentes. Favoritas del time attack.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"],"boltPatterns":["4x100","4x108","5x100","5x112","5x114.3"]}',
    '{"wheelSize":17,"wheelWidth":8,"weightReduction":8}'
),
(
    'tires-michelin-ps4s',
    'Pilot Sport 4S',
    'Michelin',
    'tires',
    1200,
    0,
    'Neumáticos de ultra alto rendimiento para uso en calle y circuito ocasional.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"tireGrip":1.15,"tireCompound":"sport"}'
),
(
    'tires-toyo-r888r',
    'Proxes R888R',
    'Toyo',
    'tires',
    1600,
    0,
    'Semi-slick de competición DOT. Máximo agarre en seco.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"tireGrip":1.35,"tireCompound":"semi-slick"}'
),
(
    'tires-pirelli-slick',
    'P Zero Trofeo RS',
    'Pirelli',
    'tires',
    2400,
    0,
    'El neumático de circuito definitivo. Desarrollado con tecnología de F1.',
    '{"mountTypes":[],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"tireGrip":1.5,"tireCompound":"semi-slick"}'
),
(
    'aero-apr-gtc500',
    'GTC-500 71',
    'APR Performance',
    'aero',
    2800,
    8,
    'Alerón de fibra de carbono con perfil alar de competición y soporte de aluminio.',
    '{"drivetrains":["FWD","RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{}'
),
(
    'brakes-ap-racing-pro',
    'AP Racing Pro 5000+',
    'AP Racing',
    'brakes',
    6200,
    10,
    'Sistema de frenos de competición profesional con discos flotantes y pinzas monobloque forjadas.',
    '{"mountTypes":[],"drivetrains":["RWD","AWD"],"engineLayouts":["front","mid","rear"]}',
    '{"brakingPower":1.75,"brakeBalance":54,"heatResistance":0.99,"weightReduction":10}'
),
(
    'suspension-oem-std',
    'Stock Suspension',
    'OEM',
    'suspension',
    0,
    0,
    'Suspensión de serie con muelles y amortiguadores estándar. Cómoda y estable para uso diario.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"springRate":1,"dampingRate":1,"rideHeight":0}'
),
(
    'suspension-sport-l1',
    'Sport Coilover L1',
    'BC Racing',
    'suspension',
    1200,
    -2,
    'Coilovers deportivos con altura regulable. Mejor manejo sin sacrificar comodidad.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"springRate":1.2,"dampingRate":1.15,"rideHeight":-25}'
),
(
    'suspension-sport-l2',
    'Sport Coilover L2',
    'KW Suspensions',
    'suspension',
    2400,
    -3,
    'Coilovers con ajuste de altura y dureza. Control total sobre el comportamiento del vehículo.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"springRate":1.35,"dampingRate":1.3,"rideHeight":-35}'
),
(
    'suspension-race-pro',
    'Race Coilover PRO',
    'Öhlins',
    'suspension',
    4800,
    -5,
    'Coilovers de competición con 20 clicks de ajuste de compresión y extensión. Muy rígidos, solo para track.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"springRate":1.6,"dampingRate":1.55,"rideHeight":-50}'
),
(
    'suspension-air-basic',
    'Basic Air Ride',
    'Air Lift',
    'suspension',
    2800,
    8,
    'Sistema de suspensión neumática básico con control manual. Perfecto para stance y show.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"springRate":0.9,"dampingRate":0.85,"rideHeight":-80}'
),
(
    'suspension-air-pro',
    'Pro Air Ride Digital',
    'Air Lift Performance',
    'suspension',
    4500,
    12,
    'Sistema neumático profesional con ECU digital y control por app. Ajuste instantáneo de altura.',
    '{"mountTypes":[],"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"springRate":1.1,"dampingRate":1,"rideHeight":-100}'
),
(
    'wheels-classic-mesh-16',
    'Classic Mesh 16',
    'BBS',
    'wheels',
    1200,
    9,
    'Llantas de aluminio estilo mesh clásico de 16 pulgadas. Look retro con buena relación peso-precio.',
    '{"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{}'
),
(
    'wheels-pro-track-18',
    'Pro Track Forged 18',
    'RAYS Volk',
    'wheels',
    3500,
    6,
    'Llantas forjadas de competición ultraligeras. Mínima masa no suspendida para máximo rendimiento.',
    '{"drivetrains":["FWD","RWD","AWD","4WD"],"engineLayouts":["front","mid","rear"]}',
    '{"weightReduction":8}'
)

ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    price = EXCLUDED.price,
    weight = EXCLUDED.weight,
    description = EXCLUDED.description,
    compatibility = EXCLUDED.compatibility,
    stats = EXCLUDED.stats,
    updated_at = NOW();
